Assignment_QLNT/Assignment_QLNT/Areas/Admin/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asm1.DATA;
using Asm1.Models;
using Microsoft.AspNetCore.Http;

namespace Asm1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/DanhMucs/")]
    public class DanhMucsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DanhMucsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/DanhMucs
        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.DanhMuc.ToListAsync());
        }
        [Route("Details/{id}")]
        // GET: Admin/DanhMucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Id == id);
            if (danhMuc == null)
            {
                return NotFound();
            }

            return View(danhMuc);
        }
        [Route("Create")]
        // GET: Admin/DanhMucs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhMuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(danhMuc);
        }
        [Route("Edit/{id}")]
        // GET: Admin/DanhMucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc.FindAsync(id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (id != danhMuc.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhMuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhMucExists(danhMuc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Delete/5
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Id == id);
            if (danhMuc == null)
            {
                return NotFound();
            }

            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhMuc = await _context.DanhMuc.FindAsync(id);
            _context.DanhMuc.Remove(danhMuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanhMucExists(int id)
        {
            return _context.DanhMuc.Any(e => e.Id == id);
        }
    }
}

Assignment_QLNT/Assignment_QLNT/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Nội thất cao cấp ChovyDecor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="shortcut icon" type="x-icon" href="\IMG\\Chovy_preview_rev_1.png">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css">
    <style>
        aside {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 20%;
            background-color: white;
            overflow-y: auto;
            box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 1px 3px 1px;
        }

        .offcanvas-body {
            padding: 20px;
        }

        .navbar-nav {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }


        .nav-item {
            margin-bottom: 10px;
            position: relative; /* Đặt vị trí tương đối để sử dụng vị trí tuyệt đối cho border */
        }

            .nav-item:hover {
                background-color: royalblue; /* Thay đổi màu nền khi hover */
                transition: 0.4s;
            }

            .nav-item::before {
                content: "";
                position: absolute;
                bottom: 0;
                left: 0;
                width: 0;
                height: 2px;
                background-color: white;
                transition: width 0.3s ease; /* Hiệu ứng chạy từ trái sang phải */
            }

            .nav-item a {
                color: black; /* Màu chữ mặc định */
                padding:20px;
            }

            .nav-item:hover::before {
                width: 100%; /* Độ rộng của border bottom */
            }

            .nav-item:hover > a {
                color: white;
                font-weight: bold;
            }
    </style>
</head>
<body>
    <aside style="width:20%">
        <div class="offcanvas-body">
            <div class="col d-flex justify-content-center">
                <img src="~/IMG/Chovy_preview_rev_1.png" width="50%" height="50%"/>

            </div>
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 col">
                <li class="nav-item  border-bottom border-1 col">
                    <a class="nav-link" aria-current="page" asp-area="Admin" asp-controller="DanhMucs" asp-action="Index">DANH MỤC SẢN PHẢM</a>
                </li>
                <li class="nav-item  border-bottom border-1 col">
                    <a class="nav-link " aria-current="page" >DANH SÁCH SẢN PHẨM</a>
                </li>
                <li class="nav-item  border-bottom border-1 col">
                    <a class="nav-link" asp-area="Admin" asp-controller="DanhMucs" asp-action="Create">THÊM DANH MỤC</a>
                </li>
                <li class="nav-item  border-bottom border-1 col">
                    <a class="nav-link" >THÊM SẢN PHẨM</a>
                </li>
                <li class="nav-item  border-bottom border-1 col">
                    <a class="nav-link" >QUẢN LÝ ĐƠN HÀNG</a>
                </li>
            </ul>
        </div>
    </aside>
    <article class="container" style="width:80%;float:right">
        <div style="height:70px; width:100%; box-shadow: 0px 1px">

        </div>
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </article>

  
   @await RenderSectionAsync("Scripts", required: false)
</body>
</html>